### ISSUE TITLE
Could not find enum constants for SHA3-256 property algorithm

### ISSUE THREAD

**Issue by esnible** [spdx/spdx-to-osv#10]
Inspired by Brandon Lum and Oliver Chang writing for the [Google Security Blog](https://security.googleblog.com/2022/06/sbom-in-action-finding-vulnerabilities.html) I tried to use this project.

I only had CycloneDX SBOMs, not SPDX SBOMs, so I converted:
```bash
curl --location https://github.com/DependencyTrack/dependency-track/releases/download/4.1.0/bom.json > /tmp/bom.json
/usr/local/Cellar/openjdk/18.0.2.1/libexec/openjdk.jdk/Contents/Home/bin/java -jar ~/src/spdx/cdx2spdx/target/cdx2spdx-0.0.2-SNAPSHOT-jar-with-dependencies.jar /tmp/bom.json /tmp/spdx-bom.json
java -jar ./target/spdx-to-osv-0.1.0-SNAPSHOT-jar-with-dependencies.jar -I /tmp/spdx-bom.json -O /tmp/OSVOutput.json
```

The error message is
```
Error reading the SPDX input file
org.spdx.library.InvalidSPDXAnalysisException: Error parsing JSON field for ID SPDXRef-pkg-maven-org.glassfish.hk2-osgi-resource-locator-1.0.3-type-jar: Could not find enum constants for SHA3-256 property algorithm
```

**Comment by goneall** [comment]
@esnible - I should have a fix for this soon - I just need to update the libraries to the latest version which supports the 2.3 spec.

**Comment by esnible** [comment]
@goneall I no longer get the error, but the contents of _/tmp/OSVOutput.json_ are merely `[]`.

**Comment by goneall** [comment]
> I no longer get the error, but the contents of /tmp/OSVOutput.json are merely []

This may be due to the return from OSV.  If you get a result different from other means, please open a new issue.
