### ISSUE TITLE
HTTP 400 Error occurs when trying to convert SPDX to OSV. (spdx-to-osv-0.1.2-jar-with-dependencies.jar)

### ISSUE THREAD

**Issue by ups-oikawa** [spdx/spdx-to-osv#30]
HTTP request body data when calling https://api.osv.dev/v1/query
It appears that purl and ecosystem are specified at the same time.

A 400 error is returned in that case.

Related Issue
https://github.com/google/osv.dev/issues/1443

**Comment by goneall** [comment]
Thanks @ups-oikawa for reporting this.

Feel free to create a pull request to fix.  Otherwise, I should be able to create a PR to fix in the next week or so.

**Comment by goneall** [comment]
@ups-oikawa I created PR #32 to resolve this issue - a bit more involved than I expected.

I'll wait a couple of days to see if there are any review comments then I'll merge / spin a new release.

**Comment by mpierrau** [comment]
Any progress here? Would love to use the tool :)

**Comment by goneall** [comment]
@mpierrau - I guess it's been more than a few days for the review - thanks for the ping.  I just merged the PR which should resolve the issue.

Let me know if you'd like me to spin a new release to Maven central.
